- name: launch instance
  hosts: localhost

  vars:
     key_name: sl_ansible

  tasks:
          #   - name: Get default VPC
          #ec2_vpc_net_facts:
          #filters:
          #   "isDefault": "true"
          #register: default_vpc
   - name: Create Sec group
      ec2_group:
         name: sec_group
         description: sec group for proj
         #description: "Sec group for "{{ id }}""
         #vpc_id: 1234
         region: us-east-1
         aws_access_key: "{{ my_access_key }}"
         aws_access_key: "{{ my_secret_key }}"
         aws_security_token: "{{ my_security_token }}"
         rules:
          - proto: tcp
            ports:
              - 22
              - 80
              - 8080
            cidr_ip: 0.0.0.0 /0
            rule_desc: allow all on ssh port
      register: result_sec_group

   - name: ec2 instance create
     ec2:
        aws_access_key:  "{{ my_access_key }}"
        aws_secret_key:  "{{ my_secret_key }}"
        aws_security_token: "{{ my_security_token }}"
        key_name: "{{ key_name }}"
        group_id: "{{ result_sec_group.group_id  }}"
        instance_type: t2.micro 
        image: ami-0279c3b3186e54acd
        region: us-east-1
        count: 1
        wait: yes
        instance_tags:
         Name: tomcat
     register: ec2

   - name: Add created instance to local host group
     ansible.builtin.lineinfile:
        path: "hosts.ini"
        create: yes
        line: "[web]"
        insertafter: "[web]"
        line: "{{ item.public_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/{{ key_name }}.pem"
     with_items: "{{ec2.instances}}"











